# Generated by Django 5.0.4 on 2024-05-01 04:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_public',
        ),
    ]
