# Generated by Django 5.0.4 on 2024-05-15 16:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20240515_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='rhythm',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='posts', to='portfolio.postrhythm', verbose_name='Ритм'),
        ),
    ]
