# Generated by Django 5.0.4 on 2024-05-23 16:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_auto_20240523_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='city',
            options={'ordering': ['country', 'name']},
        ),
    ]
